baseURL: https://rafsalrahim.io
languageCode: en-us
title: Rafsal Rahim
theme: hugo-theme-mini-master

# for exampleSite only, you may need to delete the line: `themesDir: ../../` 
themesDir: ../../

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

googleAnalytics: your-google-analytics-id
disqusShortname: rafsal

# Hugo Configure Markup
# see: https://gohugo.io/getting-started/configuration-markup#highlight
markup:
  highlight:
    guessSyntax: true
    style: emacs


# Social links in footer, support github,twitter,stackoverflow,facebook
social:
  # e.g.
  github: https://github.com/rafsalrahim
  twitter: https://twitter.com/rafsal_rahim
  stackoverflow: https://profiles.wordpress.org/rafsalrahim/
  instagram: your-github-link
  facebook: https://www.facebook.com/rafsal.rahim.1


# Site parameters
params:
  # Site Author
  author: Rafsal Rahim
  # Author biography
  bio: Software Engineer
  # Site Description, used in HTML meat
  description: My Blog
  #enableRSS: true
  # To enable comments, you may need to set `disqusShortname`
  #enableComments: true
  # To enable comments, you may need to set `googleAnalytics`
  enableGoogleAnalytics: true
  picture: "https://images.app.goo.gl/2xRFGSTcdcERZkyz8"
  # Optional
  home: '' # Default: Home
  about: '' # Default: About
  archive: '' # Default: Archive
  tags: '' # Default: Tags
  #subscribe: '' # Default: Subscribe
  olderPosts: '' # Default: Older Posts
  newerPosts: '' # Default: Newer Posts
  #copyright: '' # Default: © Copyright 2021 ❤️ author
  title404: '' # Default: 404 - Page Not Found
  subtitle404: '' # Default: The content you're looking for doesn't seem to exist.
  readMore: '' # Default: Read More

  # Extra links in navigation
  links:
    # e.g.
    # - name: Project
    #   path: /project
